import type { CanvasElement, CanvasSection } from "../useCanvasReducer";

export interface TemplatePreset {
  slug: string;
  label: string;
  emoji: string;
  category: "romantic" | "modern" | "classic" | "minimal";
  background: string;
  sections: CanvasSection[];
  elements: CanvasElement[];
  accent: string; // for thumbnail border
}

// Helper to create unique IDs
let _uid = 0;
function uid() {
  return `tpl_${Date.now()}_${++_uid}`;
}

// ── Shared text factory ──
type TextTransformType = "none" | "uppercase" | "capitalize" | "lowercase";
type TextShadowType = {
  active: boolean;
  color: string;
  blur: number;
  x: number;
  y: number;
};
 
function txt(
  sId: string,
  x: number,
  y: number,
  w: number,
  h: number,
  z: number,
  text: string,
  fontSize: number,
  fontFamily: string,
  color: string,
  opts?: Record<string, any>,
): CanvasElement {
  const textTransform: TextTransformType = opts?.textTransform ?? "none";
  const textShadow: TextShadowType = opts?.textShadow ?? {
    active: false,
    color: "#000",
    blur: 0,
    x: 0,
    y: 0,
  };
  return {
    id: uid(),
    sectionId: sId,
    type: "text",
    x,
    y,
    width: w,
    height: h,
    rotation: 0,
    opacity: opts?.opacity ?? 1,
    zIndex: z,
    locked: false,
    props: {
      text,
      fontSize,
      fontFamily,
      color,
      textAlign: "center",
      fontWeight: opts?.fontWeight ?? "normal",
      fontStyle: opts?.fontStyle ?? "normal",
      textDecoration: "none",
      lineHeight: opts?.lineHeight ?? 1.4,
      letterSpacing: opts?.letterSpacing ?? 0,
      textTransform,
      textShadow,
      backgroundColor: "",
    },
  };
}
function wgt(
  sId: string,
  x: number,
  y: number,
  w: number,
  h: number,
  z: number,
  props: Record<string, unknown>,
): CanvasElement {
  return {
    id: uid(),
    sectionId: sId,
    type: "widget",
    x,
    y,
    width: w,
    height: h,
    rotation: 0,
    opacity: 1,
    zIndex: z,
    locked: false,
    props,
  };
}

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  // ═══════════════════════════════════════════
  // 1. HOA HỒNG (Romantic)
  // ═══════════════════════════════════════════
  {
    slug: "rose-garden",
    label: "Hoa Hồng",
    emoji: "🌹",
    category: "romantic",
    background: "linear-gradient(180deg, #fce7f3 0%, #fdf2f8 30%, #fff 100%)",
    accent: "#ff6b9d",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt(
        "s1",
        60,
        30,
        280,
        35,
        1,
        "SAVE THE DATE",
        12,
        "'Cinzel', serif",
        "#be185d",
        {
          letterSpacing: 5,
          textTransform: "uppercase" as unknown as number,
          opacity: 0.6,
        },
      ),
      txt(
        "s1",
        30,
        80,
        340,
        120,
        2,
        "Tuấn Minh\n&\nMai Lan",
        36,
        "'Dancing Script', cursive",
        "#831843",
        { fontWeight: "bold", lineHeight: 1.2 },
      ),
      txt(
        "s1",
        80,
        220,
        240,
        30,
        3,
        "28 . 05 . 2026",
        20,
        "'Playfair Display', serif",
        "#9d174d",
        { letterSpacing: 4 },
      ),
      txt(
        "s1",
        30,
        310,
        330,
        160,
        4,
        "Trân trọng kính mời\n\nDự Lễ Thành Hôn\nvào 17:00, Thứ Bảy\nNgày 28 tháng 05 năm 2026\ntại Diamond Palace",
        13,
        "'Inter', sans-serif",
        "#9d174d",
        { lineHeight: 1.7 },
      ),
      txt(
        "s1",
        40,
        530,
        310,
        40,
        5,
        "Chuyện kể rằng....",
        26,
        "'Dancing Script', cursive",
        "#ff6b9d",
        { fontWeight: "bold" },
      ),
      txt(
        "s1",
        25,
        590,
        340,
        120,
        6,
        '"Tình yêu giống như một đoá hồng — cần được chăm sóc mỗi ngày để nở rộ. Và hôm nay, chúng tôi muốn chia sẻ niềm hạnh phúc ấy cùng bạn."',
        12,
        "'Inter', sans-serif",
        "#9d174d",
        { fontStyle: "italic", opacity: 0.8, lineHeight: 1.8 },
      ),
      txt(
        "s1",
        60,
        770,
        270,
        40,
        7,
        "Timeline",
        26,
        "'Dancing Script', cursive",
        "#ff6b9d",
        { fontWeight: "bold" },
      ),
      txt(
        "s1",
        20,
        830,
        110,
        50,
        8,
        "16:30\nĐón khách",
        12,
        "'Inter', sans-serif",
        "#9d174d",
        { lineHeight: 1.5 },
      ),
      txt(
        "s1",
        140,
        830,
        110,
        50,
        9,
        "17:00\nLễ cưới",
        12,
        "'Inter', sans-serif",
        "#9d174d",
        { lineHeight: 1.5 },
      ),
      txt(
        "s1",
        260,
        830,
        110,
        50,
        10,
        "18:00\nKhai tiệc",
        12,
        "'Inter', sans-serif",
        "#9d174d",
        { lineHeight: 1.5 },
      ),
      wgt("s1", 85, 950, 220, 220, 11, {
        widgetType: "calendar",
        label: "Lịch cưới",
        targetDate: "2026-05-28",
      }),
      wgt("s1", 25, 1210, 340, 100, 12, {
        widgetType: "countdown",
        label: "ĐẾM NGƯỢC NGÀY CƯỚI",
        targetDate: "2026-05-28",
      }),
      wgt("s1", 25, 1350, 340, 200, 13, {
        widgetType: "rsvp",
        rsvpTitle: "Xác nhận tham dự",
        rsvpSubtitle: "Vui lòng cho chúng tôi biết bạn có đến không",
      }),
      wgt("s1", 25, 1600, 340, 200, 14, {
        widgetType: "map",
        label: "Vị trí tiệc cưới",
        venueName: "Diamond Palace",
        venueAddress: "123 Nguyễn Huệ, Q.1, TP.HCM",
        mapUrl: "https://maps.google.com",
      }),
      wgt("s1", 25, 1850, 340, 200, 15, {
        widgetType: "gift",
        label: "Phong bì mừng cưới",
        bankName: "Vietcombank",
        accountNumber: "0123456789",
        accountName: "NGUYEN VAN A",
      }),
      txt(
        "s1",
        30,
        2100,
        330,
        80,
        16,
        "Cảm ơn bạn đã đến\nchung vui cùng chúng tôi 🌹",
        20,
        "'Dancing Script', cursive",
        "#ff6b9d",
        { fontWeight: "bold", lineHeight: 1.4 },
      ),
    ],
  },
  // ═══════════════════════════════════════════
  // 2. ĐÊM HUYỀN (Modern / Dark)
  // ═══════════════════════════════════════════
  {
    slug: "midnight-romance",
    label: "Đêm Huyền",
    emoji: "🌙",
    category: "modern",
    background:
      "linear-gradient(180deg, #0f0825 0%, #1a0a3e 30%, #2d1b69 100%)",
    accent: "#a78bfa",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt(
        "s1",
        80,
        30,
        240,
        35,
        1,
        "WE'RE GETTING MARRIED",
        11,
        "'Inter', sans-serif",
        "#c4b5fd",
        {
          letterSpacing: 4,
          textTransform: "uppercase" as unknown as number,
          opacity: 0.6,
        },
      ),
      txt(
        "s1",
        20,
        80,
        360,
        120,
        2,
        "Tuấn Minh\n&\nMai Lan",
        38,
        "'Dancing Script', cursive",
        "#e9d5ff",
        {
          fontWeight: "bold",
          lineHeight: 1.2,
          textShadow: { active: true, color: "#7c3aed", blur: 20, x: 0, y: 0 },
        },
      ),
      txt(
        "s1",
        100,
        220,
        200,
        30,
        3,
        "28 . 05 . 2026",
        18,
        "'Playfair Display', serif",
        "#c4b5fd",
        { letterSpacing: 3 },
      ),
      txt(
        "s1",
        30,
        310,
        330,
        150,
        4,
        "Trân trọng kính mời\n\nDự lễ thành hôn\nvào 17:00, Thứ bảy\nNgày 28 tháng 05 năm 2026",
        13,
        "'Inter', sans-serif",
        "#ddd6fe",
        { lineHeight: 1.7 },
      ),
      txt(
        "s1",
        40,
        520,
        310,
        40,
        5,
        "Chuyện tình của chúng tôi",
        26,
        "'Dancing Script', cursive",
        "#a78bfa",
        { fontWeight: "bold" },
      ),
      txt(
        "s1",
        25,
        580,
        340,
        120,
        6,
        '"Dưới ánh trăng huyền ảo, hai trái tim tìm thấy nhau giữa triệu vì sao. Và từ đó, mỗi đêm đều trở thành một bài thơ tình."',
        12,
        "'Inter', sans-serif",
        "#c4b5fd",
        { fontStyle: "italic", opacity: 0.8, lineHeight: 1.8 },
      ),
      txt(
        "s1",
        60,
        760,
        270,
        40,
        7,
        "Timeline",
        26,
        "'Dancing Script', cursive",
        "#a78bfa",
        { fontWeight: "bold" },
      ),
      txt(
        "s1",
        20,
        820,
        110,
        50,
        8,
        "16:30\nĐón khách",
        12,
        "'Inter', sans-serif",
        "#ddd6fe",
        { lineHeight: 1.5 },
      ),
      txt(
        "s1",
        140,
        820,
        110,
        50,
        9,
        "17:00\nLễ cưới",
        12,
        "'Inter', sans-serif",
        "#ddd6fe",
        { lineHeight: 1.5 },
      ),
      txt(
        "s1",
        260,
        820,
        110,
        50,
        10,
        "18:00\nTiệc cưới",
        12,
        "'Inter', sans-serif",
        "#ddd6fe",
        { lineHeight: 1.5 },
      ),
      wgt("s1", 85, 940, 220, 220, 11, {
        widgetType: "calendar",
        label: "Lịch cưới",
        targetDate: "2026-05-28",
      }),
      wgt("s1", 25, 1200, 340, 100, 12, {
        widgetType: "countdown",
        label: "ĐẾM NGƯỢC",
        targetDate: "2026-05-28",
      }),
      wgt("s1", 25, 1350, 340, 200, 13, {
        widgetType: "rsvp",
        rsvpTitle: "Xác nhận tham dự",
        rsvpSubtitle: "Vui lòng cho chúng tôi biết",
      }),
      wgt("s1", 25, 1600, 340, 200, 14, {
        widgetType: "map",
        label: "Vị trí tiệc cưới",
        venueName: "Star Palace",
        venueAddress: "123 Nguyễn Huệ, Q.1, TP.HCM",
        mapUrl: "https://maps.google.com",
      }),
      wgt("s1", 25, 1850, 340, 200, 15, {
        widgetType: "gift",
        label: "Phong bì mừng cưới",
        bankName: "Vietcombank",
        accountNumber: "0123456789",
        accountName: "NGUYEN VAN A",
      }),
      txt(
        "s1",
        30,
        2100,
        330,
        80,
        16,
        "Cảm ơn bạn đã đến\nchung vui cùng chúng tôi 💜",
        20,
        "'Dancing Script', cursive",
        "#c4b5fd",
        {
          fontWeight: "bold",
          lineHeight: 1.4,
          textShadow: { active: true, color: "#7c3aed", blur: 15, x: 0, y: 0 },
        },
      ),
    ],
  },
  // ═══════════════════════════════════════════
  // 3. HOÀNG HÔN (Classic / Gold)
  // ═══════════════════════════════════════════
  {
    slug: "golden-hour",
    label: "Hoàng Hôn",
    emoji: "🌅",
    category: "classic",
    background:
      "linear-gradient(180deg, #fdf6e3 0%, #fef3c7 30%, #fffbeb 100%)",
    accent: "#f59e0b",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt(
        "s1",
        60,
        30,
        280,
        35,
        1,
        "WEDDING INVITATION",
        12,
        "'Cinzel', serif",
        "#92400e",
        {
          letterSpacing: 5,
          textTransform: "uppercase" as unknown as number,
          opacity: 0.6,
        },
      ),
      txt(
        "s1",
        30,
        80,
        340,
        110,
        2,
        "Tuấn Minh\n&\nMai Lan",
        36,
        "'Great Vibes', cursive",
        "#78350f",
        { lineHeight: 1.3 },
      ),
      txt(
        "s1",
        85,
        210,
        220,
        30,
        3,
        "28 . 05 . 2026",
        20,
        "'Playfair Display', serif",
        "#b45309",
        { fontWeight: "bold", letterSpacing: 4 },
      ),
      txt(
        "s1",
        30,
        300,
        330,
        160,
        4,
        "Trân trọng kính mời\n\nQuý khách đến dự tiệc\nchung vui cùng gia đình\nvào lúc 17:00, ngày 28/05/2026\ntại Diamond Palace",
        13,
        "'Cormorant Garamond', serif",
        "#78350f",
        { lineHeight: 1.7, letterSpacing: 0.5 },
      ),
      txt(
        "s1",
        40,
        520,
        310,
        40,
        5,
        "Chuyện kể rằng....",
        26,
        "'Great Vibes', cursive",
        "#f59e0b",
      ),
      txt(
        "s1",
        25,
        580,
        340,
        120,
        6,
        '"Như ánh hoàng hôn ấm áp chiếu rọi, tình yêu của chúng tôi được thắp sáng từ những điều bình dị nhất. Bên nhau, mỗi khoảnh khắc đều trở thành vàng."',
        12,
        "'Cormorant Garamond', serif",
        "#92400e",
        {
          fontStyle: "italic",
          opacity: 0.8,
          lineHeight: 1.8,
          letterSpacing: 0.5,
        },
      ),
      txt(
        "s1",
        60,
        760,
        270,
        40,
        7,
        "Timeline",
        26,
        "'Great Vibes', cursive",
        "#f59e0b",
      ),
      txt(
        "s1",
        20,
        820,
        110,
        50,
        8,
        "16:30\nĐón khách",
        12,
        "'Cormorant Garamond', serif",
        "#78350f",
        { lineHeight: 1.5 },
      ),
      txt(
        "s1",
        140,
        820,
        110,
        50,
        9,
        "17:00\nLễ cưới",
        12,
        "'Cormorant Garamond', serif",
        "#78350f",
        { lineHeight: 1.5 },
      ),
      txt(
        "s1",
        260,
        820,
        110,
        50,
        10,
        "18:00\nKhai tiệc",
        12,
        "'Cormorant Garamond', serif",
        "#78350f",
        { lineHeight: 1.5 },
      ),
      wgt("s1", 85, 940, 220, 220, 11, {
        widgetType: "calendar",
        label: "Lịch cưới",
        targetDate: "2026-05-28",
      }),
      wgt("s1", 25, 1200, 340, 100, 12, {
        widgetType: "countdown",
        label: "ĐẾM NGƯỢC NGÀY CƯỚI",
        targetDate: "2026-05-28",
      }),
      wgt("s1", 25, 1350, 340, 200, 13, {
        widgetType: "rsvp",
        rsvpTitle: "Xác nhận tham dự",
        rsvpSubtitle: "Vui lòng xác nhận sự hiện diện của bạn",
      }),
      wgt("s1", 25, 1600, 340, 200, 14, {
        widgetType: "map",
        label: "Vị trí tiệc cưới",
        venueName: "Diamond Palace",
        venueAddress: "123 Nguyễn Huệ, Q.1, TP.HCM",
        mapUrl: "https://maps.google.com",
      }),
      wgt("s1", 25, 1850, 340, 200, 15, {
        widgetType: "gift",
        label: "Phong bì mừng cưới",
        bankName: "Vietcombank",
        accountNumber: "0123456789",
        accountName: "NGUYEN VAN A",
      }),
      txt(
        "s1",
        30,
        2100,
        330,
        80,
        16,
        "Cảm ơn bạn đã đến\nchung vui cùng chúng tôi 🌅",
        20,
        "'Great Vibes', cursive",
        "#f59e0b",
        { lineHeight: 1.4 },
      ),
    ],
  },
  // ═══════════════════════════════════════════
  // 4. ANH ĐÀO (Romantic / Pink)
  // ═══════════════════════════════════════════
  {
    slug: "cherry-blossom",
    label: "Anh Đào",
    emoji: "🌸",
    category: "romantic",
    background:
      "linear-gradient(180deg, #fdf2f8 0%, #fce7f3 40%, #fbcfe8 100%)",
    accent: "#ec4899",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt(
        "s1",
        30,
        30,
        340,
        35,
        1,
        "TOGETHER WITH THEIR FAMILIES",
        11,
        "'Inter', sans-serif",
        "#9d174d",
        {
          letterSpacing: 3,
          textTransform: "uppercase" as unknown as number,
          opacity: 0.5,
        },
      ),
      txt(
        "s1",
        20,
        80,
        360,
        120,
        2,
        "Tuấn Minh\n&\nMai Lan",
        36,
        "'Dancing Script', cursive",
        "#be185d",
        { fontWeight: "bold", lineHeight: 1.2 },
      ),
      txt(
        "s1",
        85,
        220,
        220,
        30,
        3,
        "28 . 05 . 2026",
        20,
        "'Playfair Display', serif",
        "#9d174d",
        { letterSpacing: 3 },
      ),
      txt(
        "s1",
        30,
        310,
        330,
        150,
        4,
        "Trân trọng kính mời\n\nBạn đến dự bữa tiệc hạnh phúc\nvào lúc 11:00, Thứ Bảy\nNgày 28 tháng 05 năm 2026",
        13,
        "'Inter', sans-serif",
        "#9d174d",
        { lineHeight: 1.7 },
      ),
      txt(
        "s1",
        40,
        520,
        310,
        40,
        5,
        "Love Story",
        26,
        "'Dancing Script', cursive",
        "#ec4899",
        { fontWeight: "bold" },
      ),
      txt(
        "s1",
        25,
        580,
        340,
        120,
        6,
        '"Mùa hoa anh đào nở rộ, chúng tôi gặp nhau lần đầu. Từ ánh nhìn ấy, tình yêu lớn dần như những cánh hoa bay trong gió xuân."',
        12,
        "'Inter', sans-serif",
        "#9d174d",
        { fontStyle: "italic", opacity: 0.8, lineHeight: 1.8 },
      ),
      wgt("s1", 85, 760, 220, 220, 7, {
        widgetType: "calendar",
        label: "Lịch cưới",
        targetDate: "2026-05-28",
      }),
      wgt("s1", 25, 1020, 340, 100, 8, {
        widgetType: "countdown",
        label: "ĐẾM NGƯỢC NGÀY CƯỚI",
        targetDate: "2026-05-28",
      }),
      wgt("s1", 25, 1160, 340, 200, 9, {
        widgetType: "rsvp",
        rsvpTitle: "Xác nhận tham dự",
        rsvpSubtitle: "Vui lòng cho chúng tôi biết bạn có đến không",
      }),
      wgt("s1", 25, 1410, 340, 200, 10, {
        widgetType: "map",
        label: "Vị trí tiệc cưới",
        venueName: "Palace Convention",
        venueAddress: "456 Trần Hưng Đạo, Q.5, TP.HCM",
        mapUrl: "https://maps.google.com",
      }),
      wgt("s1", 25, 1660, 340, 200, 11, {
        widgetType: "gift",
        label: "Phong bì mừng cưới",
        bankName: "Techcombank",
        accountNumber: "0987654321",
        accountName: "NGUYEN THI B",
      }),
      txt(
        "s1",
        30,
        1910,
        330,
        80,
        12,
        "Cảm ơn bạn đã đến\nchung vui cùng chúng tôi 🌸",
        20,
        "'Dancing Script', cursive",
        "#ec4899",
        { fontWeight: "bold", lineHeight: 1.4 },
      ),
    ],
  },
  // ═══════════════════════════════════════════
  // 5. BIỂN XANH (Minimal / Teal)
  // ═══════════════════════════════════════════
  {
    slug: "ocean-breeze",
    label: "Biển Xanh",
    emoji: "🌊",
    category: "minimal",
    background:
      "linear-gradient(180deg, #ecfeff 0%, #cffafe 30%, #a5f3fc 100%)",
    accent: "#06b6d4",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt(
        "s1",
        60,
        30,
        280,
        35,
        1,
        "THIỆP MỜI",
        13,
        "'Cinzel', serif",
        "#164e63",
        {
          letterSpacing: 6,
          textTransform: "uppercase" as unknown as number,
          opacity: 0.5,
        },
      ),
      txt(
        "s1",
        20,
        80,
        360,
        110,
        2,
        "Tuấn Minh\n&\nMai Lan",
        34,
        "'Dancing Script', cursive",
        "#0e7490",
        { fontWeight: "bold", lineHeight: 1.3 },
      ),
      txt(
        "s1",
        85,
        210,
        220,
        30,
        3,
        "28 . 05 . 2026",
        18,
        "'Playfair Display', serif",
        "#155e75",
        { fontWeight: "bold", letterSpacing: 4 },
      ),
      txt(
        "s1",
        30,
        300,
        330,
        150,
        4,
        "Trân trọng kính mời\n\nQuý khách đến dự tiệc\ncùng gia đình chúng tôi\nvào lúc 11:00, Chủ Nhật\nngày 28 tháng 05 năm 2026",
        13,
        "'Inter', sans-serif",
        "#164e63",
        { lineHeight: 1.7 },
      ),
      txt(
        "s1",
        40,
        510,
        310,
        40,
        5,
        "Our Love Story",
        26,
        "'Dancing Script', cursive",
        "#06b6d4",
        { fontWeight: "bold" },
      ),
      txt(
        "s1",
        25,
        570,
        340,
        100,
        6,
        '"Biển xanh mênh mông, tình yêu bao la. Chúng tôi tìm thấy nhau như hai con sóng hòa vào nhau trong ánh nắng ban mai."',
        12,
        "'Inter', sans-serif",
        "#155e75",
        { fontStyle: "italic", opacity: 0.8, lineHeight: 1.8 },
      ),
      wgt("s1", 85, 730, 220, 220, 7, {
        widgetType: "calendar",
        label: "Lịch cưới",
        targetDate: "2026-05-28",
      }),
      wgt("s1", 25, 990, 340, 100, 8, {
        widgetType: "countdown",
        label: "ĐẾM NGƯỢC NGÀY CƯỚI",
        targetDate: "2026-05-28",
      }),
      wgt("s1", 25, 1130, 340, 200, 9, {
        widgetType: "rsvp",
        rsvpTitle: "Xác nhận tham dự",
        rsvpSubtitle: "Vui lòng xác nhận sự hiện diện",
      }),
      wgt("s1", 25, 1380, 340, 200, 10, {
        widgetType: "map",
        label: "Vị trí tiệc cưới",
        venueName: "Ocean Bay Resort",
        venueAddress: "789 Trần Phú, Nha Trang",
        mapUrl: "https://maps.google.com",
      }),
      wgt("s1", 25, 1630, 340, 200, 11, {
        widgetType: "gift",
        label: "Phong bì mừng cưới",
        bankName: "MB Bank",
        accountNumber: "1122334455",
        accountName: "TRAN VAN C",
      }),
      txt(
        "s1",
        30,
        1880,
        330,
        80,
        12,
        "Cảm ơn bạn đã đến\nchung vui cùng chúng tôi 🌊",
        20,
        "'Dancing Script', cursive",
        "#06b6d4",
        { fontWeight: "bold", lineHeight: 1.4 },
      ),
    ],
  },
  // ═══════════════════════════════════════════
  // 6. CINELOVE CLASSIC (Classic / Gold — Full)
  // ═══════════════════════════════════════════
  {
    slug: "cinelove-classic",
    label: "Cinelove Classic",
    emoji: "💍",
    category: "classic",
    background:
      "linear-gradient(180deg, #faf5ef 0%, #f5ede3 30%, #faf5ef 60%, #f5ede3 100%)",
    accent: "#b8860b",
    sections: [{ id: "s1", name: "Full", height: 3200 }],
    elements: [
      txt(
        "s1",
        40,
        30,
        310,
        35,
        1,
        "SAVE THE DATE",
        12,
        "'Cinzel', serif",
        "#b8860b",
        {
          letterSpacing: 6,
          textTransform: "uppercase" as unknown as number,
          opacity: 0.5,
        },
      ),
      txt(
        "s1",
        15,
        80,
        360,
        120,
        2,
        "Tuấn Ninh\nand\nNlai Trang",
        36,
        "'Great Vibes', cursive",
        "#4a3728",
        { lineHeight: 1.3 },
      ),
      txt(
        "s1",
        65,
        220,
        260,
        30,
        3,
        "28.01.2026",
        18,
        "'Cormorant Garamond', serif",
        "#8b7355",
        { fontWeight: "bold", letterSpacing: 4 },
      ),
      txt(
        "s1",
        30,
        300,
        330,
        180,
        4,
        "Trân trọng mời Bạn\n\nDự Lễ Vu Quy\n\nVÀO 08:00, THỨ BẢY\nTHÁNG 02 — 28 — NĂM 2026\n\n(Tức ngày 8 tháng 12 năm Ất Tỵ)",
        13,
        "'Cormorant Garamond', serif",
        "#4a3728",
        { lineHeight: 1.6, letterSpacing: 1 },
      ),
      txt(
        "s1",
        60,
        500,
        270,
        70,
        5,
        "TƯ GIA NHÀ GÁI\nHÀ NỘI",
        14,
        "'Cinzel', serif",
        "#4a3728",
        {
          fontWeight: "bold",
          letterSpacing: 2,
          textTransform: "uppercase" as unknown as number,
          lineHeight: 1.5,
        },
      ),
      txt(
        "s1",
        40,
        640,
        310,
        50,
        6,
        "Chuyện kể rằng....",
        28,
        "'Great Vibes', cursive",
        "#b8860b",
        { lineHeight: 1.3 },
      ),
      txt(
        "s1",
        25,
        710,
        340,
        200,
        7,
        '"Chúng ta đã cùng nhau đi qua biết bao tháng năm, để nhận ra rằng được ở bên nhau là điều quý giá nhất.\n\nHôm nay, trước sự chứng kiến của mọi người, và khoảnh khắc này chúng ta nhẹ nhàng gọi nhau bằng hai tiếng vợ chồng"',
        12,
        "'Cormorant Garamond', serif",
        "#6b5744",
        { fontStyle: "italic", lineHeight: 1.8, letterSpacing: 0.5 },
      ),
      txt(
        "s1",
        30,
        960,
        160,
        80,
        8,
        "Chú rể\nTuấn Ninh\n16.01.2000",
        12,
        "'Cormorant Garamond', serif",
        "#4a3728",
        { lineHeight: 1.6 },
      ),
      txt(
        "s1",
        200,
        960,
        160,
        80,
        9,
        "Cô dâu\nNlai Trang\n26.01.2002",
        12,
        "'Cormorant Garamond', serif",
        "#4a3728",
        { lineHeight: 1.6 },
      ),
      txt(
        "s1",
        60,
        1100,
        270,
        40,
        10,
        "Timeline",
        28,
        "'Great Vibes', cursive",
        "#b8860b",
        { lineHeight: 1.3 },
      ),
      txt(
        "s1",
        20,
        1160,
        110,
        60,
        11,
        "08:00\nLễ thành hôn",
        12,
        "'Cormorant Garamond', serif",
        "#4a3728",
        { lineHeight: 1.5 },
      ),
      txt(
        "s1",
        140,
        1160,
        110,
        60,
        12,
        "10:30\nCheckin",
        12,
        "'Cormorant Garamond', serif",
        "#4a3728",
        { lineHeight: 1.5 },
      ),
      txt(
        "s1",
        260,
        1160,
        110,
        60,
        13,
        "11:00\nKhai tiệc",
        12,
        "'Cormorant Garamond', serif",
        "#4a3728",
        { lineHeight: 1.5 },
      ),
      txt(
        "s1",
        60,
        1280,
        270,
        40,
        14,
        "Dresscode",
        28,
        "'Great Vibes', cursive",
        "#b8860b",
        { lineHeight: 1.3 },
      ),
      txt(
        "s1",
        60,
        1330,
        270,
        30,
        15,
        "Xin vui lòng mặc trang phục theo tone màu",
        11,
        "'Cormorant Garamond', serif",
        "#6b5744",
        { fontStyle: "italic", opacity: 0.6 },
      ),
      txt(
        "s1",
        25,
        1430,
        340,
        100,
        16,
        "Rất mong bạn có thể sắp xếp tới sớm để chụp thật nhiều ảnh kỷ niệm cùng chúng mình nhé!",
        13,
        "'Cormorant Garamond', serif",
        "#4a3728",
        { lineHeight: 1.8 },
      ),
      wgt("s1", 85, 1580, 220, 220, 17, {
        widgetType: "calendar",
        label: "Tháng 2",
        targetDate: "2026-02-28",
      }),
      wgt("s1", 25, 1850, 340, 100, 18, {
        widgetType: "countdown",
        label: "ĐẾM NGƯỢC NGÀY CƯỚI",
        targetDate: "2026-02-28",
      }),
      wgt("s1", 25, 2000, 340, 200, 19, {
        widgetType: "rsvp",
        rsvpTitle: "Xác nhận tham dự",
        rsvpSubtitle: "Vui lòng cho chúng tôi biết bạn có đến không",
      }),
      wgt("s1", 25, 2250, 340, 200, 20, {
        widgetType: "map",
        label: "Vị trí tiệc cưới",
        venueName: "Tư gia nhà gái",
        venueAddress: "Hà Nội",
        mapUrl: "https://maps.google.com",
      }),
      wgt("s1", 25, 2500, 340, 200, 21, {
        widgetType: "gift",
        label: "Phong bì mừng cưới",
        bankName: "Vietcombank",
        accountNumber: "0123456789",
        accountName: "NGUYEN VAN A",
      }),
      txt(
        "s1",
        30,
        2750,
        330,
        80,
        22,
        "Cảm ơn bạn đã đến\nchung vui cùng chúng tôi 💕",
        20,
        "'Great Vibes', cursive",
        "#b8860b",
        { lineHeight: 1.4 },
      ),
    ],
  },
  // ═══════════════════════════════════════════
  // 5. ELEGANT — CineLove 36 clone (1:1 pixel-perfect)
  // ═══════════════════════════════════════════
  {
    slug: "demo-elegant",
    label: "Thiệp Cưới 36",
    emoji: "💌",
    category: "classic",
    background:
      "linear-gradient(180deg, #f5f0eb 0%, #ffffff 5%, #faf8f5 15%, #ffffff 35%, #faf7f4 55%, #ffffff 75%, #f5f0eb 100%)",
    accent: "#8b7e6a",
    sections: [{ id: "s1", name: "Full", height: 9200 }],
    elements: [
      // Quote top
      txt(
        "s1",
        30,
        40,
        360,
        80,
        1,
        "I love three things in this world.\nSun, moon and you.\nSun for morning, moon for night,\nand you forever.",
        14,
        "'Cormorant Garamond', Georgia, serif",
        "#8b7e6a",
        {
          fontStyle: "italic",
          opacity: 0.55,
          lineHeight: 1.7,
          letterSpacing: 0.5,
        },
      ),
      // Hero left photo
      {
        id: uid(),
        sectionId: "s1",
        type: "image",
        x: 0,
        y: 160,
        width: 207,
        height: 530,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        props: {
          src: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=500&h=700&fit=crop&crop=faces",
          objectFit: "cover",
        },
      },
      // Hero right photo
      {
        id: uid(),
        sectionId: "s1",
        type: "image",
        x: 213,
        y: 160,
        width: 207,
        height: 530,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        props: {
          src: "https://images.unsplash.com/photo-1519741497674-611481863552?w=500&h=700&fit=crop&crop=faces",
          objectFit: "cover",
        },
      },
      // Bride name
      txt(
        "s1",
        20,
        740,
        380,
        50,
        5,
        "Mai Anh",
        42,
        "'Great Vibes', 'Dancing Script', cursive",
        "#2c2417",
        { lineHeight: 1.2, letterSpacing: 1 },
      ),
      // Ampersand
      txt(
        "s1",
        20,
        800,
        380,
        40,
        5,
        "&",
        36,
        "'Great Vibes', 'Dancing Script', cursive",
        "#8b7e6a",
        { fontStyle: "italic", opacity: 0.5, lineHeight: 1.2 },
      ),
      // Groom name
      txt(
        "s1",
        20,
        850,
        380,
        50,
        5,
        "Minh Quân",
        42,
        "'Great Vibes', 'Dancing Script', cursive",
        "#2c2417",
        { lineHeight: 1.2, letterSpacing: 1 },
      ),
      // Poetry 1
      txt(
        "s1",
        30,
        960,
        360,
        100,
        5,
        "Đời dài muôn mảnh bình yên\nEm mang lãng mạn dịu hiền bước qua.\nSáng ngời dáng ngọc ngọc ngà\nCùng anh sánh bước chan hòa trọn đời.",
        18,
        "'Dancing Script', 'Great Vibes', cursive",
        "#5c4f3d",
        { opacity: 0.85, lineHeight: 1.8, letterSpacing: 0.3 },
      ),
      // Full-width photo 1
      {
        id: uid(),
        sectionId: "s1",
        type: "image",
        x: 0,
        y: 1150,
        width: 420,
        height: 320,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        locked: false,
        props: {
          src: "https://images.unsplash.com/photo-1529636798458-92182e662485?w=800&fit=crop",
          objectFit: "cover",
          borderRadius: 8,
        },
      },
      // Countdown
      wgt("s1", 35, 1560, 350, 120, 5, {
        widgetType: "countdown",
        label: "ĐẾM NGƯỢC",
        targetDate: "2026-06-15T10:00:00",
      }),
      // Invite message
      txt(
        "s1",
        30,
        1780,
        360,
        100,
        5,
        "Mời bạn tới dự lễ thành hôn\ncủa chúng mình\nĐể cùng chứng kiến khoảnh khắc\nthiêng liêng nhất",
        18,
        "'Dancing Script', 'Great Vibes', cursive",
        "#5c4f3d",
        { lineHeight: 1.7, letterSpacing: 0.3 },
      ),
      // Date box background
      {
        id: uid(),
        sectionId: "s1",
        type: "shape",
        x: 60,
        y: 2010,
        width: 300,
        height: 200,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        locked: false,
        props: {
          shapeType: "rectangle",
          fill: "rgba(250,248,245,0.9)",
          stroke: "rgba(212,197,169,0.3)",
          strokeWidth: 1,
          borderRadius: 16,
        } as unknown as CanvasElement["props"],
      },
      // Day number
      txt(
        "s1",
        60,
        2020,
        300,
        80,
        6,
        "15",
        72,
        "'Playfair Display', Georgia, serif",
        "#2c2417",
        { fontWeight: "bold", lineHeight: 1 },
      ),
      // Weekday
      txt(
        "s1",
        60,
        2105,
        300,
        25,
        6,
        "Chủ Nhật",
        15,
        "'Cormorant Garamond', Georgia, serif",
        "#8b7e6a",
        { opacity: 0.6, lineHeight: 1.2, letterSpacing: 3 },
      ),
      // Time + Month + Year
      txt(
        "s1",
        60,
        2140,
        140,
        20,
        6,
        "10:00 AM",
        13,
        "'Cormorant Garamond', Georgia, serif",
        "#8b7e6a",
        { opacity: 0.7, lineHeight: 1.2, letterSpacing: 1 },
      ),
      txt(
        "s1",
        160,
        2140,
        100,
        20,
        6,
        "Tháng 6",
        13,
        "'Cormorant Garamond', Georgia, serif",
        "#8b7e6a",
        { opacity: 0.7, lineHeight: 1.2, letterSpacing: 1 },
      ),
      txt(
        "s1",
        260,
        2140,
        100,
        20,
        6,
        "2026",
        13,
        "'Cormorant Garamond', Georgia, serif",
        "#8b7e6a",
        { opacity: 0.7, lineHeight: 1.2, letterSpacing: 1 },
      ),
      // Venue
      txt(
        "s1",
        20,
        2320,
        380,
        25,
        5,
        "A D D R E S S",
        12,
        "'Cormorant Garamond', Georgia, serif",
        "#8b7e6a",
        { opacity: 0.5, lineHeight: 1.2, letterSpacing: 6 },
      ),
      txt(
        "s1",
        20,
        2350,
        380,
        30,
        5,
        "Trung tâm Tiệc cưới Cinelove",
        20,
        "'Playfair Display', Georgia, serif",
        "#2c2417",
        { fontWeight: "600", lineHeight: 1.4 },
      ),
      // Full-width photo 2
      {
        id: uid(),
        sectionId: "s1",
        type: "image",
        x: 0,
        y: 2460,
        width: 420,
        height: 560,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        locked: false,
        props: {
          src: "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=800&fit=crop",
          objectFit: "cover",
        },
      },
      // English quote
      txt(
        "s1",
        40,
        3120,
        340,
        70,
        5,
        "LOVE AND FREEDOM\nYOU AND\nGENTLENESS",
        20,
        "'Cormorant Garamond', Georgia, serif",
        "#8b7e6a",
        { opacity: 0.5, lineHeight: 1.5, letterSpacing: 4 },
      ),
      // Poetry 2
      txt(
        "s1",
        30,
        3280,
        360,
        60,
        5,
        "Đời này quý giá vô ngần\nCó anh chung bước, muôn phần đẹp tươi.",
        18,
        "'Dancing Script', 'Great Vibes', cursive",
        "#5c4f3d",
        { opacity: 0.85, lineHeight: 1.8, letterSpacing: 0.3 },
      ),
      // Full-width photo 3
      {
        id: uid(),
        sectionId: "s1",
        type: "image",
        x: 0,
        y: 3450,
        width: 420,
        height: 560,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        locked: false,
        props: {
          src: "https://images.unsplash.com/photo-1544078751-58fee2d8a03b?w=800&fit=crop",
          objectFit: "cover",
        },
      },
      // Calendar
      wgt("s1", 35, 4110, 350, 320, 5, {
        widgetType: "calendar",
        label: "Tháng 6",
        targetDate: "2026-06-15",
      }),
      // Map
      wgt("s1", 35, 4530, 350, 300, 5, {
        widgetType: "map",
        label: "Vị trí tiệc cưới",
        venueName: "Trung tâm Tiệc cưới Cinelove",
        venueAddress: "123 Nguyễn Huệ, Quận 1, TP.HCM",
        mapUrl: "https://maps.google.com/?q=trung+tam+tiec+cuoi+cinelove",
      }),
      // Detail message
      txt(
        "s1",
        30,
        4930,
        360,
        140,
        5,
        "Xin vui lòng xác nhận trước với chúng mình\nsố lượng người tham dự để tiện sắp xếp chỗ ngồi.\n\nNếu có việc bận đột xuất không thể đến được,\nmong bạn báo trước.\n\nHẹn gặp bạn tại đám cưới nhé~",
        14,
        "'Cormorant Garamond', Georgia, serif",
        "#5c4f3d",
        { opacity: 0.85, lineHeight: 1.7, letterSpacing: 0.3 },
      ),
      // Full-width photo 4
      {
        id: uid(),
        sectionId: "s1",
        type: "image",
        x: 0,
        y: 5200,
        width: 420,
        height: 560,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        locked: false,
        props: {
          src: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&fit=crop",
          objectFit: "cover",
        },
      },
      // RSVP
      wgt("s1", 35, 5860, 350, 300, 5, {
        widgetType: "rsvp",
        rsvpTitle: "Xác nhận tham dự",
        rsvpSubtitle: "Vui lòng cho chúng tôi biết bạn có đến không",
      }),
      // QR Box
      wgt("s1", 35, 6260, 350, 350, 5, {
        widgetType: "gift",
        label: "Phong bì mừng cưới",
        bankName: "Vietcombank",
        accountNumber: "1234567890",
        accountName: "TRAN MAI ANH",
      }),
      // Closing poem
      txt(
        "s1",
        30,
        6720,
        360,
        100,
        5,
        "Non sông một chặng đường dài\nBa sinh hữu hạnh, duyên này thành đôi.\nTiệc vui ngắn ngủi mà thôi\nNếu điều sơ suất, mong người lượng thương.",
        18,
        "'Dancing Script', 'Great Vibes', cursive",
        "#5c4f3d",
        { opacity: 0.85, lineHeight: 1.8, letterSpacing: 0.3 },
      ),
      // Thank you
      txt(
        "s1",
        20,
        7200,
        380,
        50,
        5,
        "THANK YOU",
        36,
        "'Great Vibes', 'Dancing Script', cursive",
        "#8b7e6a",
        { opacity: 0.5, lineHeight: 1.2, letterSpacing: 3 },
      ),
    ],
  },

  // ═══════════════════════════════════════════
  // 8. LUXURY ĐEN VÀNG (Modern / Luxury)
  // ═══════════════════════════════════════════
  {
    slug: "luxury-black-gold",
    label: "Luxury Vàng",
    emoji: "✨",
    category: "modern",
    background: "linear-gradient(180deg, #0a0a0a 0%, #1a1a1a 40%, #111 100%)",
    accent: "#d4af37",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt("s1", 60, 30, 280, 35, 1, "BLACK TIE WEDDING", 11, "'Cinzel', serif", "#d4af37", { letterSpacing: 6, opacity: 0.7 }),
      txt("s1", 20, 90, 360, 130, 2, "Tuấn Minh\n&\nMai Lan", 40, "'Great Vibes', cursive", "#f5e6a3", { lineHeight: 1.2, textShadow: { active: true, color: "#d4af37", blur: 25, x: 0, y: 0 } }),
      txt("s1", 80, 240, 240, 30, 3, "28 . 05 . 2026", 20, "'Cinzel', serif", "#d4af37", { letterSpacing: 5 }),
      txt("s1", 30, 320, 340, 30, 4, "⸻⸻⸻  💍  ⸻⸻⸻", 16, "'Inter', sans-serif", "#d4af37", { opacity: 0.4 }),
      txt("s1", 30, 370, 330, 150, 5, "Trân trọng kính mời\n\nDự Lễ Thành Hôn\nvào 17:00, Thứ Bảy\nNgày 28 tháng 05 năm 2026\ntại Grand Palace Ballroom", 13, "'Cormorant Garamond', serif", "#e8d5a3", { lineHeight: 1.7 }),
      txt("s1", 40, 580, 310, 40, 6, "Our Love Story", 28, "'Great Vibes', cursive", "#d4af37", {}),
      txt("s1", 25, 640, 340, 110, 7, '"Giữa muôn vàn ánh sao đêm, chúng tôi nhận ra nhau chỉ qua một ánh nhìn. Tình yêu ấy, tinh tế như vàng, bền vững như đêm tối."', 12, "'Cormorant Garamond', serif", "#c9b87a", { fontStyle: "italic", lineHeight: 1.8 }),
      wgt("s1", 85, 810, 220, 220, 8, { widgetType: "calendar", label: "Lịch cưới", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1075, 340, 100, 9, { widgetType: "countdown", label: "ĐẾM NGƯỢC", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1225, 340, 200, 10, { widgetType: "rsvp", rsvpTitle: "Xác nhận tham dự", rsvpSubtitle: "Vui lòng phản hồi trước 28/04/2026" }),
      wgt("s1", 25, 1475, 340, 200, 11, { widgetType: "map", label: "Vị trí tiệc cưới", venueName: "Grand Palace Ballroom", venueAddress: "123 Lê Lợi, Q.1, TP.HCM", mapUrl: "https://maps.google.com" }),
      wgt("s1", 25, 1720, 340, 200, 12, { widgetType: "gift", label: "Phong bì mừng cưới", bankName: "Vietcombank", accountNumber: "0123456789", accountName: "NGUYEN VAN A" }),
      txt("s1", 30, 1970, 330, 60, 13, "Cảm ơn bạn đã đến\nchia vui cùng chúng tôi ✨", 20, "'Great Vibes', cursive", "#d4af37", { lineHeight: 1.4 }),
    ],
  },

  // ═══════════════════════════════════════════
  // 9. THIÊN NHIÊN XANH (Nature / Sage Green)
  // ═══════════════════════════════════════════
  {
    slug: "nature-garden",
    label: "Thiên Nhiên",
    emoji: "🌿",
    category: "romantic",
    background: "linear-gradient(180deg, #f0fdf4 0%, #dcfce7 30%, #bbf7d0 100%)",
    accent: "#16a34a",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt("s1", 60, 25, 280, 30, 1, "GARDEN WEDDING", 11, "'Inter', sans-serif", "#15803d", { letterSpacing: 5, opacity: 0.6 }),
      txt("s1", 20, 75, 360, 120, 2, "Tuấn Minh\n&\nMai Lan", 38, "'Dancing Script', cursive", "#166534", { fontWeight: "bold", lineHeight: 1.2 }),
      txt("s1", 80, 215, 240, 30, 3, "28 . 05 . 2026", 20, "'Playfair Display', serif", "#15803d", { letterSpacing: 3 }),
      txt("s1", 30, 305, 330, 150, 4, "Trân trọng kính mời\n\nBạn hiện diện cùng chúng tôi\nvào lúc 17:00, Thứ Bảy\nNgày 28 tháng 05 năm 2026\ntại Vườn Hoa Diamond Garden", 13, "'Inter', sans-serif", "#166534", { lineHeight: 1.7 }),
      txt("s1", 40, 515, 310, 40, 5, "Chuyện tình xanh mãi", 26, "'Dancing Script', cursive", "#22c55e", { fontWeight: "bold" }),
      txt("s1", 25, 575, 340, 110, 6, '"Giống như cây xanh cần ánh nắng để lớn, tình yêu cũng cần sự chăm sóc và trân trọng mỗi ngày. Hôm nay, chúng tôi trồng cây tình yêu ấy mãi mãi."', 12, "'Inter', sans-serif", "#15803d", { fontStyle: "italic", lineHeight: 1.8 }),
      wgt("s1", 85, 750, 220, 220, 7, { widgetType: "calendar", label: "Lịch cưới", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1010, 340, 100, 8, { widgetType: "countdown", label: "ĐẾM NGƯỢC NGÀY CƯỚI", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1160, 340, 200, 9, { widgetType: "rsvp", rsvpTitle: "Xác nhận tham dự", rsvpSubtitle: "Vui lòng cho chúng tôi biết bạn có đến không" }),
      wgt("s1", 25, 1410, 340, 200, 10, { widgetType: "map", label: "Vị trí tiệc cưới", venueName: "Diamond Garden", venueAddress: "45 Pasteur, Q.3, TP.HCM", mapUrl: "https://maps.google.com" }),
      wgt("s1", 25, 1660, 340, 200, 11, { widgetType: "gift", label: "Phong bì mừng cưới", bankName: "Techcombank", accountNumber: "9876543210", accountName: "NGUYEN MAI LAN" }),
      txt("s1", 30, 1910, 330, 60, 12, "Cảm ơn bạn đã đến\nchung vui cùng chúng tôi 🌿", 20, "'Dancing Script', cursive", "#22c55e", { lineHeight: 1.4 }),
    ],
  },

  // ═══════════════════════════════════════════
  // 10. ĐỎ VÀNG TRUYỀN THỐNG (Classic VN Red)
  // ═══════════════════════════════════════════
  {
    slug: "traditional-red-gold",
    label: "Đỏ Vàng",
    emoji: "🏮",
    category: "classic",
    background: "linear-gradient(180deg, #7f1d1d 0%, #991b1b 30%, #7f1d1d 100%)",
    accent: "#fbbf24",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt("s1", 60, 20, 280, 35, 1, "囍 THIỆP CƯỚI 囍", 20, "'Cinzel', serif", "#fbbf24", { letterSpacing: 4 }),
      txt("s1", 20, 80, 360, 130, 2, "Tuấn Minh\n&\nMai Lan", 38, "'Dancing Script', cursive", "#fef9c3", { fontWeight: "bold", lineHeight: 1.2, textShadow: { active: true, color: "#fbbf24", blur: 15, x: 0, y: 0 } }),
      txt("s1", 80, 230, 240, 30, 3, "28 . 05 . 2026", 20, "'Playfair Display', serif", "#fbbf24", { letterSpacing: 4 }),
      txt("s1", 30, 310, 330, 30, 4, "⸻⸻  ✦  ⸻⸻", 18, "'Inter', sans-serif", "#fbbf24", { opacity: 0.5 }),
      txt("s1", 30, 360, 330, 160, 5, "Kính mời\n\nQuý gia quyến\nDự Lễ Vu Quy — Lễ Thành Hôn\nvào 10:30, Thứ Bảy\nNgày 28 tháng 05 năm 2026\ntại Trung Tâm Tiệc Cưới Hoàng Gia", 13, "'Cormorant Garamond', serif", "#fef3c7", { lineHeight: 1.75 }),
      txt("s1", 40, 580, 310, 50, 6, "Nhân Duyên Trời Định", 26, "'Dancing Script', cursive", "#fbbf24", { fontWeight: "bold" }),
      txt("s1", 25, 650, 340, 110, 7, '"Từ thuở xa xôi, duyên trời đã se, hai người gặp nhau như duyên số định sẵn. Ngày vui thành hôn, kính mời quý khách chia sẻ niềm hạnh phúc."', 12, "'Cormorant Garamond', serif", "#fde68a", { fontStyle: "italic", lineHeight: 1.8 }),
      wgt("s1", 85, 820, 220, 220, 8, { widgetType: "calendar", label: "Lịch cưới", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1080, 340, 100, 9, { widgetType: "countdown", label: "ĐẾM NGƯỢC NGÀY VUI", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1230, 340, 200, 10, { widgetType: "rsvp", rsvpTitle: "Xác nhận tham dự", rsvpSubtitle: "Vui lòng hồi âm trước ngày 28/04/2026" }),
      wgt("s1", 25, 1480, 340, 200, 11, { widgetType: "map", label: "Vị trí tiệc cưới", venueName: "Hoàng Gia Palace", venueAddress: "88 Hai Bà Trưng, Q.1, TP.HCM", mapUrl: "https://maps.google.com" }),
      wgt("s1", 25, 1730, 340, 200, 12, { widgetType: "gift", label: "Mừng cưới", bankName: "VPBank", accountNumber: "1234567890", accountName: "TUAN MINH" }),
      txt("s1", 30, 1980, 330, 80, 13, "囍\nXin chân thành cảm ơn quý khách\nđã đến chung vui cùng chúng tôi.", 18, "'Cormorant Garamond', serif", "#fbbf24", { lineHeight: 1.5 }),
    ],
  },

  // ═══════════════════════════════════════════
  // 11. TỐI GIẢN TRẮNG (Minimal / Clean White)
  // ═══════════════════════════════════════════
  {
    slug: "clean-minimal-white",
    label: "Tối Giản",
    emoji: "🤍",
    category: "minimal",
    background: "#fafafa",
    accent: "#374151",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt("s1", 80, 40, 240, 20, 1, "WEDDING", 10, "'Inter', sans-serif", "#9ca3af", { letterSpacing: 8, opacity: 0.7 }),
      txt("s1", 20, 80, 360, 110, 2, "Tuấn Minh\n&\nMai Lan", 36, "'Playfair Display', serif", "#111827", { lineHeight: 1.3 }),
      txt("s1", 100, 210, 200, 2, 3, "─────────────", 14, "'Inter', sans-serif", "#d1d5db", {}),
      txt("s1", 80, 230, 240, 30, 4, "28 . 05 . 2026", 18, "'Inter', sans-serif", "#6b7280", { letterSpacing: 4 }),
      txt("s1", 30, 310, 330, 140, 5, "Trân trọng kính mời bạn\n\nDự Lễ Thành Hôn\nvào 17:00, Thứ Bảy\nNgày 28 tháng 05 năm 2026\ntại The Reverie Saigon", 13, "'Inter', sans-serif", "#374151", { lineHeight: 1.8 }),
      txt("s1", 40, 510, 310, 35, 6, "Our Story", 24, "'Playfair Display', serif", "#111827", {}),
      txt("s1", 25, 560, 340, 110, 7, '"Không có ánh hoa lộng lẫy, chỉ là những khoảnh khắc đơn giản bên nhau. Và chúng tôi nhận ra, sự bình yên cùng nhau mới là điều tuyệt vời nhất."', 12, "'Inter', sans-serif", "#6b7280", { fontStyle: "italic", lineHeight: 1.8 }),
      wgt("s1", 85, 730, 220, 220, 8, { widgetType: "calendar", label: "Lịch cưới", targetDate: "2026-05-28" }),
      wgt("s1", 25, 990, 340, 100, 9, { widgetType: "countdown", label: "ĐẾM NGƯỢC NGÀY CƯỚI", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1140, 340, 200, 10, { widgetType: "rsvp", rsvpTitle: "Xác nhận tham dự", rsvpSubtitle: "Vui lòng phản hồi trước 28/04/2026" }),
      wgt("s1", 25, 1390, 340, 200, 11, { widgetType: "map", label: "Vị trí tiệc cưới", venueName: "The Reverie Saigon", venueAddress: "22-36 Nguyễn Huệ, Q.1, TP.HCM", mapUrl: "https://maps.google.com" }),
      wgt("s1", 25, 1640, 340, 200, 12, { widgetType: "gift", label: "Phong bì mừng cưới", bankName: "ACB", accountNumber: "0987654321", accountName: "MAI LAN" }),
      txt("s1", 80, 1890, 240, 40, 13, "Thank you.", 22, "'Playfair Display', serif", "#374151", {}),
    ],
  },

  // ═══════════════════════════════════════════
  // 12. MỘNG MƠ TÍM (Lavender / Dreamy)
  // ═══════════════════════════════════════════
  {
    slug: "lavender-dream",
    label: "Mộng Mơ",
    emoji: "💜",
    category: "romantic",
    background: "linear-gradient(180deg, #faf5ff 0%, #f3e8ff 40%, #e9d5ff 100%)",
    accent: "#9333ea",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt("s1", 50, 25, 300, 30, 1, "TOGETHER FOREVER", 11, "'Inter', sans-serif", "#7e22ce", { letterSpacing: 5, opacity: 0.6 }),
      txt("s1", 20, 75, 360, 130, 2, "Tuấn Minh\n&\nMai Lan", 38, "'Dancing Script', cursive", "#581c87", { fontWeight: "bold", lineHeight: 1.2 }),
      txt("s1", 85, 225, 230, 30, 3, "28 . 05 . 2026", 20, "'Playfair Display', serif", "#7e22ce", { letterSpacing: 3 }),
      txt("s1", 30, 310, 330, 150, 4, "Trân trọng kính mời\n\nBạn dự bữa tiệc hạnh phúc\nvào 17:00, Thứ Bảy\nNgày 28 tháng 05 năm 2026\ntại Lavender Palace", 13, "'Inter', sans-serif", "#581c87", { lineHeight: 1.7 }),
      txt("s1", 40, 520, 310, 40, 5, "Chuyện Tình Mộng Mơ", 25, "'Dancing Script', cursive", "#9333ea", { fontWeight: "bold" }),
      txt("s1", 25, 580, 340, 110, 6, '"Giữa những đám mây tím mộng mơ, chúng tôi gặp nhau trong một giấc mơ đẹp. Và khi tỉnh dậy, chúng tôi nhận ra nhau đã là thực tại."', 12, "'Inter', sans-serif", "#7e22ce", { fontStyle: "italic", lineHeight: 1.8 }),
      wgt("s1", 85, 750, 220, 220, 7, { widgetType: "calendar", label: "Lịch cưới", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1010, 340, 100, 8, { widgetType: "countdown", label: "ĐẾM NGƯỢC NGÀY CƯỚI", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1160, 340, 200, 9, { widgetType: "rsvp", rsvpTitle: "Xác nhận tham dự", rsvpSubtitle: "Vui lòng cho chúng tôi biết bạn có đến không" }),
      wgt("s1", 25, 1410, 340, 200, 10, { widgetType: "map", label: "Vị trí tiệc cưới", venueName: "Lavender Palace", venueAddress: "99 Đinh Tiên Hoàng, Bình Thạnh, TP.HCM", mapUrl: "https://maps.google.com" }),
      wgt("s1", 25, 1660, 340, 200, 11, { widgetType: "gift", label: "Phong bì mừng cưới", bankName: "BIDV", accountNumber: "1122334455", accountName: "NGUYEN VAN A" }),
      txt("s1", 30, 1910, 330, 60, 12, "Cảm ơn bạn đã đến\nchung vui cùng chúng tôi 💜", 20, "'Dancing Script', cursive", "#9333ea", { lineHeight: 1.4 }),
    ],
  },

  // ═══════════════════════════════════════════
  // 13. NẮNG VÀNG RỰC (Bold Sunny / Warm Gold)
  // ═══════════════════════════════════════════
  {
    slug: "sunny-gold",
    label: "Nắng Vàng",
    emoji: "☀️",
    category: "modern",
    background: "linear-gradient(180deg, #fffbeb 0%, #fef3c7 40%, #fde68a 100%)",
    accent: "#d97706",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt("s1", 50, 25, 300, 30, 1, "✦ WEDDING INVITATION ✦", 12, "'Cinzel', serif", "#92400e", { letterSpacing: 3, opacity: 0.7 }),
      txt("s1", 20, 80, 360, 130, 2, "Tuấn Minh\n&\nMai Lan", 38, "'Great Vibes', cursive", "#78350f", { lineHeight: 1.2 }),
      txt("s1", 85, 230, 230, 30, 3, "28 . 05 . 2026", 20, "'Playfair Display', serif", "#b45309", { fontWeight: "bold", letterSpacing: 4 }),
      txt("s1", 30, 315, 330, 150, 4, "Trân trọng kính mời\n\nQuý khách dự tiệc hỷ\nvào lúc 17:00, Thứ Bảy\nNgày 28 tháng 05 năm 2026\ntại Sunshine Palace Ballroom", 13, "'Cormorant Garamond', serif", "#78350f", { lineHeight: 1.7 }),
      txt("s1", 40, 525, 310, 40, 5, "Ánh Nắng Tình Yêu", 26, "'Great Vibes', cursive", "#d97706", {}),
      txt("s1", 25, 585, 340, 110, 6, '"Như ánh mặt trời chiếu rọi mỗi sáng, tình yêu của chúng tôi cũng ấm áp và trung thành. Ngày hôm nay, chúng tôi chia sẻ ánh nắng ấy với bạn."', 12, "'Cormorant Garamond', serif", "#92400e", { fontStyle: "italic", lineHeight: 1.8 }),
      wgt("s1", 85, 755, 220, 220, 7, { widgetType: "calendar", label: "Lịch cưới", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1015, 340, 100, 8, { widgetType: "countdown", label: "ĐẾM NGƯỢC NGÀY VUI", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1165, 340, 200, 9, { widgetType: "rsvp", rsvpTitle: "Xác nhận tham dự", rsvpSubtitle: "Vui lòng phản hồi trước 28/04/2026" }),
      wgt("s1", 25, 1415, 340, 200, 10, { widgetType: "map", label: "Vị trí tiệc cưới", venueName: "Sunshine Palace", venueAddress: "150 Bến Vân Đồn, Q.4, TP.HCM", mapUrl: "https://maps.google.com" }),
      wgt("s1", 25, 1665, 340, 200, 11, { widgetType: "gift", label: "Mừng cưới", bankName: "MB Bank", accountNumber: "1230456789", accountName: "NGUYEN VAN A" }),
      txt("s1", 30, 1915, 330, 60, 12, "Cảm ơn bạn đã đến\nchung vui cùng chúng tôi ☀️", 20, "'Great Vibes', cursive", "#d97706", { lineHeight: 1.4 }),
    ],
  },

  // ═══════════════════════════════════════════
  // 14. XANH BIỂN (Ocean Blue / Coastal)
  // ═══════════════════════════════════════════
  {
    slug: "ocean-blue",
    label: "Xanh Biển",
    emoji: "🌊",
    category: "modern",
    background: "linear-gradient(180deg, #eff6ff 0%, #dbeafe 30%, #bfdbfe 100%)",
    accent: "#2563eb",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt("s1", 50, 25, 300, 30, 1, "OCEAN WEDDING", 12, "'Inter', sans-serif", "#1d4ed8", { letterSpacing: 5, opacity: 0.6 }),
      txt("s1", 20, 75, 360, 130, 2, "Tuấn Minh\n&\nMai Lan", 38, "'Dancing Script', cursive", "#1e3a8a", { fontWeight: "bold", lineHeight: 1.2 }),
      txt("s1", 85, 225, 230, 30, 3, "28 . 05 . 2026", 20, "'Playfair Display', serif", "#1d4ed8", { letterSpacing: 3 }),
      txt("s1", 30, 310, 330, 150, 4, "Trân trọng kính mời\n\nBạn dự Lễ Thành Hôn\nvào lúc 17:00, Thứ Bảy\nNgày 28 tháng 05 năm 2026\ntại Oceanfront Resort & Spa", 13, "'Inter', sans-serif", "#1e3a8a", { lineHeight: 1.7 }),
      txt("s1", 40, 520, 310, 40, 5, "Giữa Đại Dương Tình Yêu", 24, "'Dancing Script', cursive", "#2563eb", { fontWeight: "bold" }),
      txt("s1", 25, 580, 340, 110, 6, '"Như sóng biển vỗ mãi vào bờ, tình yêu của chúng tôi không ngừng nghỉ. Mỗi ngày là một con sóng mới, mang theo những yêu thương vô tận."', 12, "'Inter', sans-serif", "#1d4ed8", { fontStyle: "italic", lineHeight: 1.8 }),
      wgt("s1", 85, 750, 220, 220, 7, { widgetType: "calendar", label: "Lịch cưới", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1010, 340, 100, 8, { widgetType: "countdown", label: "ĐẾM NGƯỢC NGÀY CƯỚI", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1160, 340, 200, 9, { widgetType: "rsvp", rsvpTitle: "Xác nhận tham dự", rsvpSubtitle: "Vui lòng phản hồi trước 28/04" }),
      wgt("s1", 25, 1410, 340, 200, 10, { widgetType: "map", label: "Vị trí tiệc cưới", venueName: "Oceanfront Resort", venueAddress: "Bãi Biển Long Hải, Vũng Tàu", mapUrl: "https://maps.google.com" }),
      wgt("s1", 25, 1660, 340, 200, 11, { widgetType: "gift", label: "Phong bì mừng cưới", bankName: "Sacombank", accountNumber: "0011223344", accountName: "MAI LAN" }),
      txt("s1", 30, 1910, 330, 60, 12, "Cảm ơn bạn đã đến\nchia vui cùng chúng tôi 🌊", 20, "'Dancing Script', cursive", "#2563eb", { lineHeight: 1.4 }),
    ],
  },

  // ═══════════════════════════════════════════
  // 15. ĐỒNG QUÊ (Rustic / Vintage Farmhouse)
  // ═══════════════════════════════════════════
  {
    slug: "rustic-vintage",
    label: "Đồng Quê",
    emoji: "🌾",
    category: "classic",
    background: "linear-gradient(180deg, #fdfcfb 0%, #fdf8f0 40%, #f9f1e4 100%)",
    accent: "#92400e",
    sections: [{ id: "s1", name: "Full", height: 3000 }],
    elements: [
      txt("s1", 50, 20, 300, 28, 1, "✿ RUSTIC WEDDING ✿", 12, "'Cinzel', serif", "#78350f", { letterSpacing: 4, opacity: 0.65 }),
      txt("s1", 20, 70, 360, 130, 2, "Tuấn Minh\n&\nMai Lan", 38, "'Dancing Script', cursive", "#5c2d0e", { fontWeight: "bold", lineHeight: 1.2 }),
      txt("s1", 85, 220, 230, 30, 3, "28 . 05 . 2026", 20, "'Playfair Display', serif", "#92400e", { letterSpacing: 3 }),
      txt("s1", 30, 305, 330, 150, 4, "Trân trọng kính mời\n\nBạn dự tiệc hỷ\nvào lúc 17:00, Thứ Bảy\nNgày 28 tháng 05 năm 2026\ntại Finca Del Sol Garden\nTiền Giang", 13, "'Cormorant Garamond', serif", "#78350f", { lineHeight: 1.7 }),
      txt("s1", 40, 520, 310, 40, 5, "Chuyện Tình Đồng Quê", 25, "'Dancing Script', cursive", "#b45309", {}),
      txt("s1", 25, 580, 340, 110, 6, '"Trên cánh đồng vàng óng, giữa hương thơm của đất và lúa, chúng tôi tìm thấy nhau. Tình yêu đơn sơ mà sâu sắc, như quê hương trong tim."', 12, "'Cormorant Garamond', serif", "#78350f", { fontStyle: "italic", lineHeight: 1.8 }),
      wgt("s1", 85, 750, 220, 220, 7, { widgetType: "calendar", label: "Lịch cưới", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1010, 340, 100, 8, { widgetType: "countdown", label: "ĐẾM NGƯỢC NGÀY CƯỚI", targetDate: "2026-05-28" }),
      wgt("s1", 25, 1160, 340, 200, 9, { widgetType: "rsvp", rsvpTitle: "Xác nhận tham dự", rsvpSubtitle: "Vui lòng phản hồi trước 28/04" }),
      wgt("s1", 25, 1410, 340, 200, 10, { widgetType: "map", label: "Vị trí tiệc cưới", venueName: "Finca Del Sol Garden", venueAddress: "Xã Thạnh Phú, Tiền Giang", mapUrl: "https://maps.google.com" }),
      wgt("s1", 25, 1660, 340, 200, 11, { widgetType: "gift", label: "Mừng cưới", bankName: "Agribank", accountNumber: "9988776655", accountName: "NGUYEN VAN A" }),
      txt("s1", 30, 1910, 330, 60, 12, "Cảm ơn bạn đã đến\nchia vui cùng chúng tôi 🌾", 20, "'Dancing Script', cursive", "#b45309", { lineHeight: 1.4 }),
    ],
  },
];

export const TEMPLATE_CATEGORIES = [
  { key: "all", label: "Tất cả" },
  { key: "romantic", label: "Lãng mạn" },
  { key: "modern", label: "Hiện đại" },
  { key: "classic", label: "Cổ điển" },
  { key: "minimal", label: "Tối giản" },
];
